[workspace]
resolver = "2"
members = ["crates/core", "crates/cli", "crates/wasm", "crates/server"]
default-members = ["crates/core", "crates/cli", "crates/server"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/anon5376/git-fight"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "warn"
